[package]
name = "akartui-rs"
version = "0.1.0"
edition = "2021"

[dependencies]

serde = { version = "1.0.219", features = ["derive"] }
crossterm = "0.29.0"
ratatui = "0.29.0"
serde_json = "1.0.140"
